// Generated by scripts/generate-ascii-portrait.mjs.
// Re-run `pnpm generate:portrait`; use `node scripts/generate-ascii-portrait.mjs --size 120 --output -` for a 120x120 matrix.
export const ASCII_PORTRAIT_SOURCE = "public/images/me.jpg";
export const ASCII_PORTRAIT_WIDTH = 37;
export const ASCII_PORTRAIT_HEIGHT = 16;
export const ASCII_PORTRAIT_MATCHER = "glyph";
export const ASCII_PORTRAIT_RENDERER = "browser";
export const ASCII_PORTRAIT_CHARSET_NAME = "latin1";
export const ASCII_PORTRAIT_CHARSET =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ";
export const ASCII_PORTRAIT =
  '                ¸¸                   \n         ¸,-¬-¯_²¯-¯²-.¸             \n       ¸/j²j²UjJjCjJ»ijJ²,¸          \n      _-J¯    ¯`"¯`    ¯Uj¯,         \n    -"²/                 ¹ª²         \n     UJ                   jU         \n     j»`  ¸_¸_     ¸_,_¸` ¹J`        \n    ¸²J-¬²"¯"ª²ª¬²j"¯j¯¯¯"¯U-¸       \n    ¯\\"¹¸ ¯²¯`¯j¯ U²¸"¸` ¸²j¹´       \n    ´_j ¯-¸,¸-ª`   ¯-¬-¬-¯ "-        \n     ¹[¸     `~-,_-¹° ¸   ¸j´        \n      ¯j-¸-²-²"²ª¯"¯²j²\\ -¨²         \n       ²¯² " ´ - -·¸` ¸-/¸/`         \n        jJ-²-¸ ¨¬~²´¸-¯²ªU`          \n       ,²¯"ji¯²¸¯¸¯-¯¹¸j¨²-¸         \n  ¸_-²¯j-\\  ¯¹ªj²-ji»"`  ¯"¯-¯-.¸¸   ';
