// Generated by scripts/generate-ascii-portrait.mjs.
// Re-run `pnpm generate:portrait`; use `node scripts/generate-ascii-portrait.mjs --size 120 --output -` for a 120x120 matrix.
export const ASCII_PORTRAIT_SOURCE = "public/images/me.jpg";
export const ASCII_PORTRAIT_WIDTH = 64;
export const ASCII_PORTRAIT_HEIGHT = 24;
export const ASCII_PORTRAIT_MATCHER = "glyph";
export const ASCII_PORTRAIT_RENDERER = "browser";
export const ASCII_PORTRAIT_CHARSET_NAME = "latin1";
export const ASCII_PORTRAIT_CHARSET =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ";
export const ASCII_PORTRAIT =
  '                      ¸_¸,¸-¯¸¯²-²¸¨²"-¸                        \n                   ,²¯-¯-jª²¬ª-j¯-´-¯¸¨`-¯²¬¸                   \n                 ,UjU²¬U²+¬jU²"J"j²ª/«²jUj\\J¯\\¸                 \n                -²JHJ¯    ¯²+(\\jUª"¯    ´¯«ji_¯²¸               \n             ¸,j²j"`                       ´²Uj ¯,              \n            ,"UiU`                           ¯U²¸\\              \n            ²Jj"¯ ¸                           -ª¯j              \n            ´U²U¸ ´                           ¬jJ)              \n             jJj² ¸                           ´UCª              \n             ªU¾  `·_-=jªjUj¸`   ¸¨_U¾UÜJUj-,_¸_²J              \n            ¸²jJ²"²"¯´¯¸¯¯_¯"j²"²"j¯¸,-¸,¸   ¯j"¾ª¯¹            \n           -`¸ªj\\j ¸ ²ªjUJ¯¹¸JU¯´ª1-²¯JU(²"¸` 1²U¸(¸`           \n           ³¸²Ui U,´·  ¸`¸.´-Ùj   \\j`-`·     ,j j,´,            \n            \\`/Ú ´\\-¸_,_,_-/²`     ¯²:¬-¬-«»²¯  (¯-`            \n             ¹·U-   ´`´`   j ¸     ¸ j         ¸"¸²             \n             ¯¸j\\      ¸  `¯"¯"-,-²¯,¸`¸\',     -¬,¨             \n              `ª/-_  ¸-\\-jJªUÚjU²jJ\\ª\\²"²j¯- ¸,¸\\               \n               ´U"²-`´²j`¬»-·-·-`-·`°¯ª¯ )" ,¯-¯j               \n                ²jJ¯²¸-²   ´¯`¸·¬¸´¯¸   -²¸-²¸¬J`               \n                 ¯Uj-¯¬"-,   ·"¹:°"-   ¸/¨¬j«jª                 \n                 ¸²¾UjJj¸¹¸¸`¸¸-¯¸¹¸`¸-¯-²J²(H~¸                \n                -"Jj´²U²(-¨,-,¨¹`-¨-¯´²¸_jU/ -¹¨,               \n             ¸_,²¸¯U   ¯«U²Uj(j¸¨¸²¸_jUJi¯   ¯Ú¸²"-,¸           \n        ¸_,-"¯-j-/-¸¹¸    ¯"²«¯J²j(J²"¯      -²` ¹ª_¸¯²-¬,¸`    ';
