// Generated by scripts/generate-ascii-portrait.mjs.
// Re-run `pnpm generate:portrait`.
export const ASCII_PORTRAIT_SOURCE = "public/images/me.jpg";
export const ASCII_PORTRAIT_WIDTH = 37;
export const ASCII_PORTRAIT_HEIGHT = 16;
export const ASCII_PORTRAIT_MATCHER = "glyph";
export const ASCII_PORTRAIT_RENDERER = "browser";
export const ASCII_PORTRAIT_CHARSET_NAME = "latin1";
export const ASCII_PORTRAIT_CHARSET =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ";
export const ASCII_PORTRAIT =
  '                              ¸      \n                ¸             ¹  ¸ ¸ \n              _,_j©«U²-_      ¸      \n             ´²´` ²j¾Ú¾Ú¾_    ¹      \n                 ´-¯²¯²¯Ü²    ¸      \n            ¸_¸_¸_¸¸ ¸-"-J    `      \n             `     ` ´`´¯¸    ¸      \n           `  ¸ ¹-¸ -¸·¸_,    `      \n              ¹-¯j` `_-Ú²jUj¸ , ¸ ¸_¸\n          ¸. ~JÚ¾²-´,Ú¾©JÜ¾²-U¹ `    \n        -_-`   ¸`  /²¯j²ÚjªÚ¯²j_  `  \n        ²"    ´jJ·,-jJU"¾Ü²¾Ù¾Ú²U¸   \n       ¸ ¸_   ¸-¯ ²U²¾²Ü©Hj-j©j¾©²_  \n    ¸` -¯²¯,  U²j¸j-j-¯¾Ú¾U²ÚJ²-U-Ú¹¸\n    ´¸«²jÚ_²´-¾-(Ú¾U²U²j²©Ü¯¾Ü¾Ü¾j¾-¯\n    ²Ú-Ú©JÜjUjÚ²j²j©¾©Ú¾Ú-²Ú²©HjÚ©ÚjÚ';
