// Generated by scripts/generate-ascii-portrait.mjs.
// Re-run `pnpm generate:portrait`; use `node scripts/generate-ascii-portrait.mjs --size 120 --output -` for a 120x120 matrix.
export const ASCII_PORTRAIT_SOURCE = "public/images/me.jpg";
export const ASCII_PORTRAIT_WIDTH = 64;
export const ASCII_PORTRAIT_HEIGHT = 24;
export const ASCII_PORTRAIT_MATCHER = "glyph";
export const ASCII_PORTRAIT_RENDERER = "browser";
export const ASCII_PORTRAIT_CHARSET_NAME = "latin1";
export const ASCII_PORTRAIT_CHARSET =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ";
export const ASCII_PORTRAIT =
  '                       ¸ ¸¸_¸-²"jªU²j-¸¸                        \n                   _-²ÚjJÚ¾UÜ¾¯ÚJÜ-U¯Jj²-¯¸-¸             ¸     \n                 -U¾Ú¾JÙHª²JHjU¾ªU²"²"-ªj²¬²¯-¸                 \n                 ²ÜHU"¯¸´¸¯"²"ª²J¯`¸    ´¯"U¾j,¸          ¸     \n              _-"Úª¯¸`¸-`·`¸`¸`´¸ ·´ `     ´²Ú¾-¯               \n            ¸jÚ¾Ü²¸`-¯´¹¸¨¸·´·¸·`¸`¸·¸ ¸     ¯j²¸`              \n            ´ÜHUª¨-¸²¸-¸-¹`¸`¸`¸´·´ ¨`·`      ´-¯¸              \n             j¾Ü²¸`¯-¨¹¨¸¨-´·´·¨¸`¸`¸ ¸        ¸`·              \n             ²Új"-¸²¸-¸-¹¸¹¸-¸-¸·¨-´·`·`¸`     ´¸¨              \n             ¬U¾¯`¯-jU¾U¾Uj«j²j²-²_jJUJÚ¾j_,_¸¸·-¸              \n             -ª½UHU¾ª"ªjJ1Ú¾U¾Ú¾Ú¾Ú1j1j-,¸´¸`-¾Ú²`·¸            \n            jJU¾ª¾jJU¾Ú¾Ú¾HÜHÜHU¯ª¼U¾UJ¾"ª²¯·¸²¯¸ ¯`            \n            ²¯²Ú¯Ú²"²jJjJjUJª¾ªj²¸¯j²«j-¸`¸ `´/ - ´             \n            ´-J¾-"¾j_-_²iJjUÜ"²¯-´¸´ª»+«,-,-·¯  ¯¸              \n             ¨²U²¸¨¸²"¯"¯U¾J²jij¸¯·¸`¯-²¸¨¸     -`              \n              -J¯-²-¨¸-¸²-¯ªUÜ¾UJ²¸"¯¸´¯"j²-¸   ¸·              \n               ²j«j¸`²jUjU²Ú¾JÚªU¾U²-`·¸²-Jj`¸`¸¨`              \n               ´Ú¾J²-¯ªC²¾Hjij«²-`·¨¸´²"¯j²¯·-´·¸               \n                ²UÜ¾U¸²U¯¸²"²¯-¸´¸´¸·   ¸J-¸`¸`-                \n                 ¯¼ÚjÜ¾jJ-¨¸-¸²¯-`·`   `_¯¸²-,²                 \n                 ¸j¾ÙHÚÜ¾j²_¨`-¸´¸´¸ ¸-¸²-`,¬`¸                 \n                `ªÚ-ª¾UJÚÜ¾ª²j²¯-,²-¨²¨·¨¸²´  j-                \n              ¸_²j¾jJj²ª¾HUÚ¾ÚJjJUjJjª-j-´   -Ú² -¸             \n         ¸_-j²Új-ÚÜ²ªUJ-j²"ªH©U¾ª¾²ª²"¨     ¸jª¯ ´²-¸`¸`¸ ¸     ';
