// Generated by scripts/generate-ascii-portrait.mjs.
// Re-run `pnpm generate:portrait`; use `node scripts/generate-ascii-portrait.mjs --size 120 --output -` for a 120x120 matrix.
export const ASCII_PORTRAIT_SOURCE = "public/images/me.jpg";
export const ASCII_PORTRAIT_WIDTH = 37;
export const ASCII_PORTRAIT_HEIGHT = 16;
export const ASCII_PORTRAIT_MATCHER = "glyph";
export const ASCII_PORTRAIT_RENDERER = "browser";
export const ASCII_PORTRAIT_CHARSET_NAME = "latin1";
export const ASCII_PORTRAIT_CHARSET =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ";
export const ASCII_PORTRAIT =
  '                                     \n             ¸_,_,¹j-¸_              \n           ¸U©ª²ªUJ¯`¯-,_            \n          _j¯¸          ¯¹¸          \n         ¹Ú¸-`-¸`  ¸      ¨          \n         ´j¨¸´¸¨-¸`  ¸    ¸          \n         ¸²-²"²"j«»²¯_`¸¨-`          \n         ¯j´¸¯¸¯²´¸´¸·    ¸          \n          ²-²-¹"-¯·  ¯¸`  `          \n          ¯_´¸¯jJ²¸-¸ -²¸ ¸          \n           ª²_²"ª¯´  `¸¯·`           \n            jÚ¾¸-¸-`  -¸-¸           \n          ¸²\\¯²¯¹_²j_¯¸¨ ²           \n      _-_²-¯Ú-j-¸¯"´`   _" ¹¸ ¸`     \n ¸_-²"²¯"Ú¾Ü²¯_`·`¸   ¸-¯,¸ ¯ ¨-¸`¸  \n²-²´¸¯¸U²j©"Új¾²_´ ´-_²j" ¹ ¸ ¸´-´-´ ';
